### ISSUE TITLE
Dragging tabs crashes the editor

### ISSUE THREAD

**Issue by noySq** [SkEditorTeam/SkEditor#126]
Using 2.8.2

Crash log:
```
System.MissingMethodException: Method not found: 'Void Avalonia.Controls.Primitives.IPopupHost.ConfigurePosition(Avalonia.Visual, Avalonia.Controls.PlacementMode, Avalonia.Point, Avalonia.Controls.Primitives.PopupPositioning.PopupAnchor, Avalonia.Controls.Primitives.PopupPositioning.PopupGravity, Avalonia.Controls.Primitives.PopupPositioning.PopupPositionerConstraintAdjustment, System.Nullable`1<Avalonia.Rect>)'.
   at FluentAvalonia.UI.Controls.Primitives.TabViewListView.HandleReorder(Point panelPoint)
   at FluentAvalonia.UI.Controls.Primitives.TabViewListView.OnDragOver(Object sender, DragEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(Interactive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.DragDropDevice.RaiseDragEvent(Interactive target, IInputRoot inputRoot, Point point, RoutedEvent`1 routedEvent, DragDropEffects operation, IDataObject data, KeyModifiers modifiers)
   at Avalonia.Input.DragDropDevice.DragOver(IInputRoot inputRoot, Point point, IDataObject data, DragDropEffects effects, KeyModifiers modifiers)
   at Avalonia.Input.DragDropDevice.ProcessRawEvent(RawDragEvent e)
   at Avalonia.Threading.Dispatcher.Send(SendOrPostCallback action, Object arg, Nullable`1 priority)
```

**Comment by NotroDev** [comment]
Hey, thanks for the issue! Someone has already reported it - I'll fix it soon.
